import { test, expect } from '@playwright/test'

const dashboard = 'Your hours at a glance.'

test('logging hours works with nothing but the prefilled defaults', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: dashboard })).toBeVisible()
  await page.getByRole('button', { name: 'Log hours', exact: true }).first().click()
  await page.getByLabel('Hours', { exact: true }).fill('1.5')
  await page.getByLabel('Notes').fill('Playwright private entry')
  await page.getByRole('button', { name: 'Save entry' }).click()
  await expect(page.getByText('Playwright private entry')).toBeVisible()
  await expect(page.getByText('1.5 h').first()).toBeVisible()
})

test('direct, indirect, and supervision hours summon the matching activity dropdown', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Log hours', exact: true }).first().click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('radio', { name: /Direct hours/ })).toBeVisible()
  const direct = dialog.getByLabel('Direct activity')
  await expect(direct).toBeVisible()
  await expect(direct.locator('option', { hasText: 'Intake Interviewing/Assessment' })).toHaveCount(1)
  await expect(direct.locator('option', { hasText: 'Individual Counseling' })).toHaveCount(1)
  await dialog.getByRole('radio', { name: /Indirect hours/ }).click()
  const indirect = dialog.getByLabel('Indirect activity')
  await expect(indirect.locator('option', { hasText: 'Record Keeping' })).toHaveCount(1)
  await expect(indirect.locator('option', { hasText: 'Administrative Tasks' })).toHaveCount(1)
  await expect(indirect.locator('option', { hasText: 'Supervision' })).toHaveCount(0)
  await dialog.getByRole('radio', { name: /^Supervision/ }).click()
  const supervision = dialog.getByLabel('Supervision', { exact: true })
  await expect(supervision.locator('option', { hasText: 'Individual Supervision' })).toHaveCount(1)
  await expect(supervision.locator('option', { hasText: 'Group Supervision' })).toHaveCount(1)
  await dialog.getByRole('radio', { name: /Indirect hours/ }).click()
  await dialog.getByLabel('Hours', { exact: true }).fill('2')
  await dialog.getByLabel('Notes').fill('Indirect write-up')
  await dialog.getByRole('button', { name: 'Save entry' }).click()
  await expect(page.getByText('Indirect write-up')).toBeVisible()
})
test('the quick pick keeps the hours field in step', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Log hours', exact: true }).first().click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: '0.5 h', exact: true }).click()
  await expect(dialog.getByLabel('Hours', { exact: true })).toHaveValue('0.5')
  await dialog.getByRole('button', { name: 'Save entry' }).click()
  await expect(page.getByRole('heading', { name: dashboard })).toBeVisible()
})

test('a day on the calendar logs hours against that date', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Calendar' }).click()
  await page.getByRole('button', { name: /^Log hours on / }).click()
  await page.getByLabel('Notes').fill('Logged from the calendar')
  await page.getByRole('button', { name: 'Save entry' }).click()
  await expect(page.getByText('Logged from the calendar')).toBeVisible()
})

test('a batch of drafts stays in a table and saves together', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Log hours', exact: true }).first().click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Hours', { exact: true }).fill('0.75')
  await dialog.getByLabel('Notes').fill('Repeated supervision')
  await dialog.getByRole('button', { name: 'Add another', exact: true }).click()
  const table = dialog.getByRole('table', { name: 'Entries to save' })
  await expect(table.getByRole('row')).toHaveCount(3)
  await dialog.getByRole('button', { name: 'Previous day' }).click()
  await dialog.getByLabel('Notes').fill('Adjusted second')
  await expect(dialog.getByRole('button', { name: 'Save 2 entries' })).toBeVisible()
  await table.getByRole('row').nth(1).getByRole('button').first().click()
  await expect(dialog.getByLabel('Notes')).toHaveValue('Repeated supervision')
  await expect(dialog.getByLabel('Hours', { exact: true })).toHaveValue('0.75')
  await dialog.getByRole('button', { name: 'Save 2 entries' }).click()
  await expect(page.getByRole('status')).toContainText('2 entries logged')
  await expect(page.getByText('Repeated supervision')).toBeVisible()
  await expect(page.getByText('Adjusted second')).toBeVisible()
})

test('an entry without hours explains itself instead of failing silently', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Log hours', exact: true }).first().click()
  await page.getByLabel('Hours', { exact: true }).fill('0')
  await page.getByRole('button', { name: 'Save entry' }).click()
  await expect(page.getByRole('alert')).toContainText('how many hours')
})

test('signing out is a no-op in local mode and the workspace remains', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Local & private')).toBeVisible()
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: dashboard })).toBeVisible()
})

test('every page keeps a way back to the dashboard', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Settings' }).click()
  await expect(page.getByRole('heading', { name: 'Settings & data' })).toBeVisible()
  await expect(page.getByText('Add activity type')).toHaveCount(0)
  await expect(page.getByLabel('Add supervisor')).toHaveCount(0)
  await page.getByRole('button', { name: 'Dashboard' }).click()
  await expect(page.getByRole('heading', { name: dashboard })).toBeVisible()
  await page.getByRole('button', { name: 'Reports' }).click()
  await expect(page.getByRole('heading', { name: /Activity Summary/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Hours summary' })).toBeVisible()
  await page.getByRole('button', { name: 'the Hours of Pee — go to overview' }).click()
  await expect(page.getByRole('heading', { name: dashboard })).toBeVisible()
})

test('placement separates hours by job and is where supervisors are added', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Placement', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Placement', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Community placement' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'School counseling site' })).toBeVisible()
  await expect(page.getByLabel('Add supervisor')).toBeVisible()
  await page.getByRole('button', { name: 'View hours' }).first().click()
  await expect(page.getByText('Hours at this site')).toBeVisible()
  await page.getByRole('button', { name: 'All placements' }).click()
  await expect(page.getByRole('heading', { name: 'Placement', exact: true })).toBeVisible()
})

test.describe('remote flows', () => {
  test.skip(!process.env.PLAYWRIGHT_REMOTE, 'Set PLAYWRIGHT_REMOTE=1 with a seeded Supabase project to run online tests.')
  test('accepting an invitation', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
  test('registering and confirming account state', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
  test('signing in', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
  test('logging private hours', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
  test('signing out and back in', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
  test('verifying data persistence on another browser context', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
  test('failed access to another user’s data', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
  test('admin invitation flow', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
  test('suspension flow', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
  test('local-data migration', async () => { expect(process.env.PLAYWRIGHT_REMOTE).toBeTruthy() })
})
